version: '3.8'

services:
  nginx_proxy:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
  spring_api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: spring_api
    restart: always
    ports:
      - "8080:8080"
